apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: secret
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: ${IMAGE_REPOSITORY}/secret
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: secret
      chartPath: deploy/helm
      valuesFiles:
      - ${VALUES_LOCATION}/secret.yaml
